### ISSUE TITLE
Website form 'Readme.md' is offline!

### ISSUE THREAD

**Issue by TDRMinecraft** [RootRobo/linux-ng-audio-dl#3]
The website from [Readme](https://github.com/RootRobo/linux-ng-audio-dl/blob/master/README.md) isn't available.

Website: https://rootrobo.ddns.net/newgrounds/

Thanks from @TDRMinecraft

**Comment by RootRobo** [comment]
I already know about this and I am looking into finding a solution, hosting a public website at home when the internet connection crashes frequently is not optimal. I will update this issue when I have a solution.

**Comment by RootRobo** [comment]
I am working on a full JavaScript version of this page that can be hosted on GitHub.

**Comment by RootRobo** [comment]
The JavaScript Version is done and can be found [here](https://rootrobo.github.io/newgrounds-audio-downloader/)
The GitHub repo is [here](https://github.com/RootRobo/newgrounds-audio-downloader)

**Comment by RootRobo** [comment]
I am going to close this issue, as the PHP+Bash version on the website was no longer maintained anyway. If you have further questions just open a new issue.
